# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

THIS REPOSITORY IS PRIVATE DON'T COPY IT, COPYRIGHTED BY AM INDUSTRY'S

<iframe width="420" height="345" src="https://www.techtoam.online">
</iframe>

<button class = "custom-btn btn-12"> <a onclick="JoinMe()"><span>Thanks For Joining ♥️</span><span> Join now </span></button>

<script>
function JoinMe() {
  location.replace("https://bit.ly/__join_now__")
}
</script>
