# These are supported funding model platforms

github:  TECHTOAMYT
patreon: https://www.techtoam.online/payme
open_collective: https://www.techtoam.online/payme
custom: https://www.techtoam.online/payme
